before_script: curl -sSL https://raw.githubusercontent.com/luketaverne/travis-solr/master/travis-solr.sh | SOLR_VERSION=5.0.0 bash
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.1.1'
